spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/sbproject1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or create / create-drop for testing
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 9090